// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundKeepAPI.Models;

namespace SoundKeepAPI.Migrations
{
    [DbContext(typeof(SoundKeepAPIContext))]
    [Migration("20181122070912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SoundKeepAPI.Models.TrackItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist");

                    b.Property<string>("ArtworkURL");

                    b.Property<string>("Comment");

                    b.Property<string>("DateAdded");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.Property<string>("TrackID");

                    b.Property<string>("TrackURL");

                    b.HasKey("ID");

                    b.ToTable("TrackItem");
                });
#pragma warning restore 612, 618
        }
    }
}
